//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H
#define PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H

void ValidateNumber(int Number);

#endif //PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H
