//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H
#define PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H

#include <stdlib.h>

void ValidateValue(int Value);

#endif //PROBLEMSOLVINGARHITECTURE_VALIDATIONSDEF_H
