//
// Created by cigan on 14.10.2020.
//

#ifndef CONTROLDIGITFORNUMBER_VALIDATIONSIMPLEMENTATION_H
#define CONTROLDIGITFORNUMBER_VALIDATIONSIMPLEMENTATION_H

#include "ValidationsDef.h"

void ValidateNumber(int Number) {

    if (Number <= 0)
        FAIL_EXIT;
}
#endif //CONTROLDIGITFORNUMBER_VALIDATIONSIMPLEMENTATION_H
