//
// Created by cigan on 15.10.2020.
//

#ifndef PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
#define PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H

#include "ValidationsDef.h"

void ValidateValue(int Value) {

    if (Value <= 0)
        exit(1);
}

#endif //PROBLEMSOLVINGARHITECTURE_VALIDATIONSIMPLEMENTATION_H
